### ISSUE TITLE
Oraganisation - access to hardware repository

### ISSUE THREAD

**Issue by rhfogh** [mxcube/mxcubeweb#880]
Hi, This is for discussion - we may not agree. 

Trying to find my way around mscube3, I found it tricky to get around access to the hardware repository.
First, the name for the variable holding the hardware repository client is mxcube.mxcubecore, where it is mostly 'hwr' in the mxcubecore repository. It would be nice to use the same name throughout.
Second, access to the hardware repository in mxcube is through the mscube app. This means that you cannot access the hardware repository before the app is instantiated - which gave me a problem with circular imports when trying to do a bug fix. 
It also means that a number of functions that do not need the app, in core/utils can only be accessed from mxcube3.

So could we consider:
- harmonising the naming used for the hardwarerepository object across the two repositories?
- Accessing directly through the mxcubecore code in files where the app is not needed?
- Moving functions that do not need anything from mxcube3, such as str_to_snake_case, to a mxcubecore utils file, so that they are not limited to use only within mxcube3?

If we do decide that something should be changing, I can do the refactoring at some point. But first we need to agree if it should be done.

Rasmus

**Comment by beteva** [comment]
@rhfogh, it is always good to have new look at the code and suggest improvement. I would like to understand, though, the changes you want to discuss with few concrete examples. Unfortunately I do not quite see what do you mean by accessing directly or not the mxcubecore code when the app is not needed. Also I find a bit dangerous to mix the HWR of the HardwareRepository with the mxcubecore access from the application, but maybe I do not quite understand your needs.
As for the functions, no problem moving to utils file, but when do you want to use them, if not in mxcube3?

**Comment by rhfogh** [comment]
I am still not on top of how mxcube3 is put together, and some of this may be the usual growing pains when getting used to something new. 

What started this was actually a bug fix. The code in app.py required the str_to_snake function, but you cannot import that in app.py at the top level, because core.utils imports MXCUBEApplication, so you get into circular imports. Thre are ways around that, of course, but on general principle I thought it would be better that straight functions with no dependencies like str_to_snake should not be put in a file where you need the MXCUBEApplication to access them. You might want them in mxcubecore, for instance, so that might be a better place for them. 
So: put functions that do not need teh mxcube app into utils files in mxcubecore, or at least avoid importing the app in those files.

For the access, it is currently set in app.py that 
MXCUBECore.beamline_ho = mxcubecore.HardwareRepository.beamline
A file like wfutils.py, for instance, does
from mxcube3 import mxcube
only so that it can later get the beamline as 
mxcube.mxcubecore.beamline_ho
This adds an unnecessary dependence on the app, which could be avoided by doing instead
 from mxcubecore.HardwareRepository import beamline as beamline_ho
So: get the beamline directly from mxcubecore.HardwareRepository, at least where you do not need the app for other reasons.

In general there seems to be two main access paths, one via the HardwareRepositoryCLient, accessed as HardwareRepository.get_hardware_repository(), the other as hardwareRepositiry.beamline. I suspect that is a matter of a still incomplete transition, to a new way fo handling this, but if you already have an idea how this should end up looking, I could think about making small moves in that direction.

**Comment by marcus-oscarsson** [comment]
Hi Both,

I'm actually on vacation but taking some time to answer a few mails and other things. My responses are therefore with some delay.

I appreciate your question and it is a relevant topic to discuss. I also understand that it might be somewhat confusing to get into the code base as, you correctly pointed out, its a bit in transition phase.

The original idea with using the Application object like: `from mxcube3 import mxcube` was to simply encapsulate not only
HardwareRepository but also other things that are often needed. Simply to reduce the imports and provide a centralized 
access to i.e HardwareRepository. 

I understand that this is can be confusing if you are used to work with HardwareRepository, whats perhaps worse is that this can easily lead to a situation with circular imports (as I think you've also noticed)

We are currently moving away from accessing "singleton" like objects like `Application` and the `HardwareRepository Beamline object` through `import`.  The reason being that its harder to control when those objects are initialized/accessed, leading to circular imports and initialization race conditions, if done through imports rather than if they are encapsulated in an object and explicitly initialized. The drawback is that this object then needs to be "passed around" to be accessed.

So we are currently transitioning into a solution were the `Application` object is passed to the parts of the code that needs it. This will remove the need for the `from mxcube3 import mxcube` import. I don't think we will need the explicit import `from mxcubecore.HardwareRepository import beamline as beamline_ho` but I agree that its better to use this over `from mxcube3 import mxcube` (if it cant be avoided).

We should perhaps perform a group review of the work done in the [mxcubecore branch](https://github.com/mxcube/mxcube3/tree/mxcubecore) that at least partly addresses of these topics.

Ill be back from vacation in about a weeks time, we can try to schedule something for then if @beteva  and @meguiraun is also available. For instance around the 18th and 19th of August ?

**Comment by rhfogh** [comment]
Can I re-raise this point:

Occasioned by a bug ('mxcube' left in the code) I had occasion to try to track where e.g. the beamline_ho came from.
It is accessed by 
'self.app.mxcubecore.beamline_ho' (in sampleview.py).
Analysing further one finds that 'mxcubecore' is *not* related to the mxcubecore repository, but is a custom object created in app.
Analysing still further one finds that the beamline_ho is originally accessed as

from mxcubecore import HardwareRepository as hwr
beamline_ho = hwr.get_hardware_repository().beamline

In short, this is not a replacement for an import statement (which is a goal I would tend to share). It is simply a complex set of syntactic sugar to hide the fact that we are actually using an import statement, and the mxcubecore-level central access object, i.e. hwr. 

Centralising all object access in a custom structure under self.app may be a very useful move for programming the mxcube interface. It does however have the drawbacks that
- it is MXCuBE3 specific and so cannot be used in mxcubecore or mxcubeqt
- it necessarily duplicates the access structure that is (and must be) in mxcubecore, forcing people to keep track of two different ways of accessing objects
- It makes mxcube3 code 'mxcube-3-only', making it harder to use even quite simple code outside its original context. 


Can we have a discussion, so it is clear what the agreed way to access central objects should be, and what is the reasoning behind it??

**Comment by marcus-oscarsson** [comment]
Yes you can :), Thanks for the input and keeping the discussion alive :) I think this can amount to quite a lengthy discussion and I think it would be more efficiently conducted in our bi-weekly meeting (next one is the 16th). We
can then discuss the reason behind this and what we should do. Would that be alright or is it more urgent that in
your opinion ?

In the meantime please have a look at #893 were I addressed some of the points you mention above (We touched in this subject a few dev-meetings ago so I started to do something about it :) ).

**Comment by rhfogh** [comment]
Taking this up in our meetings sounds like exactly the right approach.

Yes, I had noticed you had addressed the point already (just after I wrote my contribution). Thanks. I shall address it as soon as I am out of PSDI2021.

**Comment by marcus-oscarsson** [comment]
Solved
